# Generated by Django 4.2.23 on 2025-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_control', '0002_userlockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=16)),
            ],
        ),
    ]
