# Generated by Django 4.2.23 on 2025-07-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_control', '0003_iplockout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplockout',
            name='addr',
        ),
        migrations.AddField(
            model_name='iplockout',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
