services:
  socweb-profiles:
    restart: always
    mem_limit: 500M
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    ports:
      - "${HTTP_PORT:-8003}:${HTTP_PORT:-8003}"
    labels:
      - "a=axasocweb"
      - "traefik.enable=true"
      - "traefik.http.routers.profiles.rule=PathPrefix(`/api/v1/profile`)"
      - "traefik.http.routers.profiles.entrypoints=web"

networks:
  default:
    name: axanetwork
    external: true
