# Generated by Django 4.2 on 2025-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="text",
        ),
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default="", verbose_name="Основной текст статьи"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="", verbose_name="Заголовок"),
            preserve_default=False,
        ),
    ]
