name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set short SHA
      id: vars
      run: |
        echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Configure Docker daemon for insecure registry
      run: |
        echo '{"insecure-registries":["10.166.44.63"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Install WireGuard
      run: sudo apt-get update && sudo apt-get install -y wireguard resolvconf

    - name: Configure WireGuard
      run: |
        echo "${{ vars.WIREGUARD_CONF }}" > wg0.conf
        sudo mv wg0.conf /etc/wireguard/wg0.conf
        sudo wg-quick up wg0

    - name: Log in to Harbor Registry
      run: |
        echo "${{ vars.HARBOR_PASSWORD }}" | docker login ${{ vars.HARBOR_URL }} -u ${{ vars.HARBOR_USERNAME }} --password-stdin

    - name: Build and push Docker image Backend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ vars.HARBOR_URL }}/stream/chat-service:${{ env.COMMIT_SHORT_SHA }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ vars.KUBECONFIG }}" > $HOME/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.0

    - name: Deploy with Helm
      run: |
        echo "Generated values.yaml ..."
        echo "${{vars.VALUES}}" > .helm/values.yaml 
        helm upgrade --install -n stream chat-service .helm/ --set image.tag=${{ env.COMMIT_SHORT_SHA }}
