# Generated by Django 4.2.23 on 2025-06-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='geo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='screen',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
