# Generated by Django 4.2.23 on 2025-06-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_loginevent_geo_alter_loginevent_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_to_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
