# Generated by Django 4.2.23 on 2025-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_to_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_to_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
