 # Generated by Django 4.2.23 on 2025-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_to_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16),
        ),
    ]