# Generated by Django 4.2.23 on 2025-07-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginevent_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginEvent',
        ),
    ]
