# Generated by Django 4.2.23 on 2025-07-31 02:14

from django.conf import settings  # type: ignore
from django.db import migrations, models  # type: ignore
import django.db.models.deletion  # type: ignore
import timezone_field.fields  # type: ignore


def create_user_profiles(apps, schema_editor):
    """Создает профили для всех существующих пользователей"""
    User = apps.get_model(settings.AUTH_USER_MODEL.split(
        '.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for user in User.objects.all():
        # Проверяем, существует ли уже профиль (на случай повторного применения)
        if not hasattr(user, 'user_profiles'):
            UserProfile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(
                    help_text='Основной аккаунт, к которому привязан этот профиль',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='user_profiles',
                    serialize=False,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Связанный пользователь',
                )),
                ('time_zone', timezone_field.fields.TimeZoneField(
                    choices_display='WITH_GMT_OFFSET',
                    default='Europe/Moscow',
                    help_text='Используется для корректного отображения времени в системе',
                    use_pytz=False,
                    verbose_name='Часовой пояс',
                )),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_profiles',
            },
        ),
        migrations.RunPython(create_user_profiles,
                             reverse_code=migrations.RunPython.noop),
    ]
