# Generated by Django 4.2.23 on 2025-08-12 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Role name')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Background image'),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Backup email'),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Backup phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='is user subjected to 2FA when is authenticating (set by user)', verbose_name='2FA enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('stock_market', 'Stock Market'), ('crypto', 'Crypto'), ('forex', 'Forex')], max_length=20, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, hyphens and underscores', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='Verification method'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_to_2fa',
            field=models.BooleanField(default=True, help_text='is user subjected to 2FA when is registering (set by admin)'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userrole', verbose_name='Role'),
        ),
    ]
