# Generated by Django 4.2.23 on 2025-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='is the account to be physically deleted (set by user)', verbose_name='Is account deleted'),
        ),
    ]
