# Generated by Django 4.2.23 on 2025-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time of deletion request'),
        ),
    ]
