# Generated by Django 4.2.24 on 2025-09-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_deletion_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название сектора')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='sector',
        ),
        migrations.AddField(
            model_name='user',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='accounts.sector', verbose_name='Секторы'),
        ),
    ]
