# Generated by Django 4.2.24 on 2025-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sector_remove_user_sector_user_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_to_2fa',
        ),
    ]
