services:
  socweb-posts-service:
    restart: always
    mem_limit: 500M
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    ports:
      - "${HTTP_PORT:-8004}:${HTTP_PORT:-8004}"
    labels:
      - "a=axasocweb"
      - "traefik.enable=true"
      - "traefik.http.routers.posts.rule=PathPrefix(`/api/v1/posts`)"
      - "traefik.http.routers.posts.entrypoints=web"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"    
    networks:
      - default

networks:
  default:
    name: axanetwork
    external: true
